# Generated by Django 3.2.5 on 2021-07-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
