# Generated by Django 3.2.5 on 2021-07-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('events', '0002_alter_assignment_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='member',
        ),
        migrations.AddField(
            model_name='assignment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
