# Generated by Django 3.2.5 on 2021-07-12 05:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_visited_at'),
        ('events', '0003_auto_20210711_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('member', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
