# Generated by Django 3.2.5 on 2021-07-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_assignment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='avalibality',
            field=models.BooleanField(default=False),
        ),
    ]
