# Generated by Django 3.2.5 on 2021-07-05 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
