# Generated by Django 3.2.5 on 2021-07-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.session'),
            preserve_default=False,
        ),
    ]
