# Generated by Django 3.2.5 on 2021-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='visited_at',
            field=models.DateField(auto_now=True),
        ),
    ]
