# Generated by Django 3.2.5 on 2021-07-02 05:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dep_status', models.CharField(choices=[('Lunched', 'Lunched'), ('Lunching', 'Lunching'), ('Not Available', 'Not Available')], default='Lunched', max_length=20)),
                ('dep_publish_date', models.DateField()),
            ],
        ),
    ]
