# Generated by Django 3.2.5 on 2021-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumUploadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upload', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='curriculum/list/')),
            ],
        ),
    ]
