# Generated by Django 3.2.5 on 2021-07-19 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_curriculumuploadlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='curr_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
