# Generated by Django 3.2.5 on 2021-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_curriculum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
